export interface WorkerEnv {
  PARTY_ROOM: DurableObjectNamespace;
}

// Normally generated by `wrangler types`; hand-written here to keep the build
// dependency-free. Lets `cloudflare:test`'s `env` (typed as `Cloudflare.Env`)
// resolve to our actual bindings in tests. Named WorkerEnv, not Env, so this
// doesn't self-reference inside the `namespace Cloudflare { interface Env }`
// block below (an `Env` declared there would shadow the outer one).
declare global {
  namespace Cloudflare {
    interface Env extends WorkerEnv {}
  }
}
